version: "3.8"
services:

  antity:
    build: ./
    container_name: antity
    volumes:
      - ./:/usr/src/app
      - antity_node_modules:/usr/src/app/node_modules


volumes:
  antity_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules